### PR TITLE
useContext fixed/little css clean

### PR DESCRIPTION
**Pull request by nueladeyemi1**
Hi Vidhanvyrs,
I fixed the context and I tested to ensure that nothing breaks.
Also, did a little touch on some CSS before checking out because I saw that the responsive issue has been assigned to @ShanieshaJ #9

### CODE REVIEW

**Comment by ShanieshaJ** [comment]
> Hi Vidhanvyrs, I fixed the context and I tested to ensure that nothing breaks. Also, did a little touch on some CSS before checking out because I saw that the responsive issue has been assigned to @ShanieshaJ #9

I see that you added some touches to the CSS. I have not started working on it until everything is working smoothly and merged before I can work on doing the responsive part.

**Comment by nueladeyemi1** [comment]
> > Hi Vidhanvyrs, I fixed the context and I tested to ensure that nothing breaks. Also, did a little touch on some CSS before checking out because I saw that the responsive issue has been assigned to @ShanieshaJ #9
> 
> I see that you added some touches to the CSS. I have not started working on it until everything is working smoothly and merged before I can work on doing the responsive part.

Yeah! I wouldn’t want to touch it further because I never knew if you had started.

That’s nice, it’s good you want to ensure everything is working smoothly before starting.


Good working with you here! I’d be following.

**Comment by ShanieshaJ** [comment]
> > > Hi Vidhanvyrs, I fixed the context and I tested to ensure that nothing breaks. Also, did a little touch on some CSS before checking out because I saw that the responsive issue has been assigned to @ShanieshaJ #9
> > 
> > 
> > I see that you added some touches to the CSS. I have not started working on it until everything is working smoothly and merged before I can work on doing the responsive part.
> 
> Yeah! I wouldn’t want to touch it further because I never knew if you had started.
> 
> That’s nice, it’s good you want to ensure everything is working smoothly before starting.
> 
> Good working with you here! I’d be following.

Oh, I almost forgot to mention that there is an issue with the Netlify deploying part where it gives the error message on the Main.js file where useState is defined and not used. Which is causing the checks to fail.

**Comment by Vidhanvyrs** [comment]
thanx for your contribution @nueladeyemi1 I'll review the code tomorrow and give you the feedback and as @ShanieshaJ suggested please resolve those issue with the checks 
Again thanx  @nueladeyemi1 and @ShanieshaJ for consistently keeping up with the project

**Comment by Vidhanvyrs** [comment]
yeah so i have not reviewed the code yet but on seeing deployment i can see some issues here
image
can you make both the size of div somewhat bigger and also the left div with the weather content inside please give some padding to the contents in it and also make sure that design of the search bar restored you see that old design was intentionally put there that is the search icon placed inside the input, and there is some padding/margin issue with the globe too
The rest of the feedback i will give you tomorrow until then please resolve these one if possible

**Comment by nueladeyemi1** [comment]
> > > > Hi Vidhanvyrs, I fixed the context and I tested to ensure that nothing breaks. Also, did a little touch on some CSS before checking out because I saw that the responsive issue has been assigned to @ShanieshaJ #9
> > > 
> > > 
> > > I see that you added some touches to the CSS. I have not started working on it until everything is working smoothly and merged before I can work on doing the responsive part.
> > 
> > 
> > Yeah! I wouldn’t want to touch it further because I never knew if you had started.
> > That’s nice, it’s good you want to ensure everything is working smoothly before starting.
> > Good working with you here! I’d be following.
> 
> Oh, I almost forgot to mention that there is an issue with the Netlify deploying part where it gives the error message on the Main.js file where useState is defined and not used. Which is causing the checks to fail.

Thank you, I thought I removed the useState as eslint notified me before I deployed. I adjusted it already.

**Comment by nueladeyemi1** [comment]
> yeah so i have not reviewed the code yet but on seeing deployment i can see some issues here image can you make both the size of div somewhat bigger and also the left div with the weather content inside please give some padding to the contents in it and also make sure that design of the search bar restored you see that old design was intentionally put there that is the search icon placed inside the input, and there is some padding/margin issue with the globe too The rest of the feedback i will give you tomorrow until then please resolve these one if possible

I adjusted the earlier issue and reversed the css and flow back to the initial state with the context fixed, do let know if there is any issue.

**Comment by Vidhanvyrs** [comment]
It Looks and works great !! thanx for contributing

**Pull request merged**
